
language: python
sudo: false
python:
- '3.5.2'

addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-postgis-2.3

cache:
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install ansible
  - pip install -r requirements/development.txt

before_script:
- export DATABASE_URL=postgres://postgres@localhost/finbouquet
- psql -c "CREATE DATABASE finbouquet;" -U postgres

script:
- flake8
- py.test --cov -v --tb=native
- ansible-playbook -i provisioner/hosts provisioner/site.yml --syntax-check

notifications:
  email:
    on_success: change  # [always|never|change]
    on_failure: always  # [always|never|change]
